### ISSUE TITLE
NER部分 keras backend出错

### ISSUE THREAD

**Issue by Dwyane3** [yongzhuo/nlp_xiaojiang#6]
Traceback (most recent call last):
  File "/home/l/Dwyane/NLP-pack/nlp_xiaojiang/Ner/bert/keras_bert_ner_bi_lstm.py", line 343, in <module>
    train()
  File "/home/l/Dwyane/NLP-pack/nlp_xiaojiang/Ner/bert/keras_bert_ner_bi_lstm.py", line 297, in train
    bert_model = BertNerBiLstmModel()
  File "/home/l/Dwyane/NLP-pack/nlp_xiaojiang/Ner/bert/keras_bert_ner_bi_lstm.py", line 65, in __init__
    self.build_model_bilstm_layers()
  File "/home/l/Dwyane/NLP-pack/nlp_xiaojiang/Ner/bert/keras_bert_ner_bi_lstm.py", line 138, in build_model_bilstm_layers
    output_layers = crf(dense_layer)
  File "/home/l/.local/lib/python3.6/site-packages/keras/engine/base_layer.py", line 451, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/l/Dwyane/NLP-pack/nlp_xiaojiang/Ner/bert/keras_bert_layer.py", line 481, in call
    test_output = self.viterbi_decoding(X, mask)
  File "/home/l/Dwyane/NLP-pack/nlp_xiaojiang/Ner/bert/keras_bert_layer.py", line 776, in viterbi_decoding
    input_length=K.int_shape(X)[1], unroll=self.unroll)
  File "/home/l/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 3188, in rnn
    output, _ = step_function(inputs[0], initial_states + constants)
  File "/home/l/Dwyane/NLP-pack/nlp_xiaojiang/Ner/bert/keras_bert_layer.py", line 769, in find_path
    next_best_idx = gather_each_row(argmin_table, best_idx[0][:, 0])
  File "/home/l/Dwyane/NLP-pack/nlp_xiaojiang/Ner/bert/keras_bert_layer.py", line 765, in gather_each_row
    indices = K.transpose(K.stack([K.tf.range(n), indices]))
AttributeError: module 'keras.backend' has no attribute 'tf'

**Comment by yongzhuo** [comment]
可能是keras版本问题，我用的是keras=2.2.4，因为官方项目的（keras-team/keras-contrib）也是这么写的。此外，这个CRF版本似乎也有问题的，训练的时候loss会降到负数，建议你参考一下:[https://github.com/BrikerMan/Kashgari/blob/master/kashgari/layers/crf.py](https://github.com/BrikerMan/Kashgari/blob/master/kashgari/layers/crf.py)

**Comment by Dwyane3** [comment]
已确认是keras版本问题，之前的版本高于2.2.4，改回2.2.4可以正常运行
